### PR TITLE
fix(tests): use chrome for unit tests instead of phantomjs

### PR DESCRIPTION
**Pull request by jarifibrahim**
This PR 
 - Removes phantomjs from package.json
 - Installs chrome in the CI docker container

### CODE REVIEW

**Comment by aptmac** [comment]
Perhaps its outside of the scope of this PR in particular, but there are only 3 unit tests actually being run at the moment [[0]](https://ci.centos.org/job/devtools-ngx-widgets/220/console), because the markdown component [[1]](https://github.com/fabric8-ui/ngx-widgets/blob/master/src/app/markdown/markdown.component.spec.ts) has `fit` instead of `it` on each of it's 3 unit tests .. would you be able to change them and see how the rest of the tests perform? Unless the `fit` was an intentional addition of https://github.com/fabric8-ui/ngx-widgets/pull/148 ? @sanbornsen 

[0] https://ci.centos.org/job/devtools-ngx-widgets/220/console
[1] https://github.com/fabric8-ui/ngx-widgets/blob/master/src/app/markdown/markdown.component.spec.ts

**Comment by rohitkrai03** [comment]
@jarifibrahim This commit https://github.com/fabric8-ui/ngx-widgets/pull/150/commits/083bbd378f4cf278dbb1cf8cbbe80f7cc1b68c8e adds the same functionality i think. Its part of this PR - https://github.com/fabric8-ui/ngx-widgets/pull/150 which is going to be merged soon.

**Comment by aptmac** [comment]
@rohitkrai03 Good find! Yeah, it looks there are existing plans to use headless chrome and re-enable the unit tests.

**Comment by jarifibrahim** [comment]
@aptmac Since the all the unit tests will be enabled in https://github.com/fabric8-ui/ngx-widgets/pull/150, should we merge this PR?

**Comment by joshuawilson** [comment]
I think a lot of this will be fixed by the upgrade.

**Comment by jarifibrahim** [comment]
>I think a lot of this will be fixed by the upgrade.

@joshuawilson so should we merge this PR?

**Comment by joshuawilson** [comment]
working on it now, should be ready today or tomorrow at the latest

**Comment by joshuawilson** [comment]
oh, sorry, this PR not the upgrade. Let me finish the upgrade and then anything left over you can submit a PR for that. The upgrade and this would be a hard rebase.

**Comment by joshuawilson** [comment]
This was taken care of in the upgrade. If you still want to remove references to PhantomJS, please submit a new PR.

**Pull request closed without merging**
