### PR TITLE
Update Packages

### PR DESCRIPTION
**Pull request by joshuawilson**
Angular 6.1.0

### CODE REVIEW

**Comment by joshuawilson** [comment]
[test]

**Comment by jiekang** [comment]
Analysis of test failure:

```
FAILED TESTS:
  GitHubLinkArea component - 
    ✖ Should render links from the server side rendering correctly.
      HeadlessChrome 0.0.0 (Linux 0.0.0)
    Expected true to be falsy.
```

There is no expect for falsy in GitHubLinkArea test. This suggests there is another test that is not running correctly, with an expectation being called after the test is considered complete.

Searches for 'falsy' lead to a possible culprit:

```
dialog.component.spec.ts:
[...]
  it('Clicking a button will close the dialog.', () => {
    comp.dialog = dialog;
    fixture.detectChanges();
    comp.btnClick(0);
    setTimeout(() => {
      expect(comp.modalFadeIn).toBeFalsy();
    }, 300); // 300ms takes to close the modal
  });
[...]
```

`The `setTimeout` call is async, the test should be written with an async testing system. Using the `DoneFn` is one possibility (Angular has a variety of ways to handle async tests).

**Comment by jiekang** [comment]
@joshuawilson Maybe try:

```
diff --git a/src/app/dialog/dialog.component.spec.ts b/src/app/dialog/dialog.component.spec.ts
index 813dee5..d154278 100644
--- a/src/app/dialog/dialog.component.spec.ts
+++ b/src/app/dialog/dialog.component.spec.ts
@@ -95,12 +95,13 @@ describe('Dialog component - ', () => {
     expect(el.children.length).toBe(comp.dialog.actionButtons.length);
   });
 
-  it('Clicking a button will close the dialog.', () => {
+  it('Clicking a button will close the dialog.', (done: DoneFn) => {
     comp.dialog = dialog;
     fixture.detectChanges();
     comp.btnClick(0);
     setTimeout(() => {
       expect(comp.modalFadeIn).toBeFalsy();
+      done();
     }, 300); // 300ms takes to close the modal
   });
 ```

and see where things go?

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
