### PR TITLE
fix(markdown): Fixed markdown component with undefined values.

### PR DESCRIPTION
**Pull request by sanbornsen**
Fixing OSIO issue 1443 - 
https://openshift.io/openshiftio/openshiftio/plan/detail/3a331aa3-6423-4fd7-85e4-95d7932b168c

### CODE REVIEW

**Comment by aslakknutsen** [comment]
@sanbornsen This probably fixes this specific issue, but missing a fix to the general problem. Why/How can a random sub component somewhere miss behave and break the whole UI? @joshuawilson

**Comment by joshuawilson** [comment]
Can you show me how to reproduce the issue?

**Comment by aslakknutsen** [comment]
@joshuawilson See OSiO issue in Description

**Comment by sanbornsen** [comment]
@aslakknutsen I believe if we turn off the debug mode it'll not fail on random child failure. There should be something. I'll look into it.

**Comment by sanbornsen** [comment]
# Do not merger 
# Not fixed yet

**Comment by joshuawilson** [comment]
When I run the example, I can add text to the new "undefined section" but it doesn't display when select the checkmark.

**Comment by sanbornsen** [comment]
@joshuawilson yeah, that is the idea. Even after adding a text if your backend returns undefined for some reason it doesn't show anything without failing the component.

**Pull request merged**
