### PR TITLE
fix(release): fix failing build

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by joshuawilson** [comment]
The `build` step is vital, this is not a functional work around.

**Comment by rawlingsj** [comment]
please don't close PRs that I'm using to fix CI, I've just wasted 10 mins thinking a build was running after pushing another change to this PR.

**Comment by rawlingsj** [comment]
@joshuawilson ^^

**Comment by joshuawilson** [comment]
Sorry @rawlingsj I thought you wanted this PR merged if it fixed it. Since it didn't, I closed it. I didn't want anyone else merging this hoping to apply the fix.

**Pull request closed without merging**
